
tracks:

  bp-prod-php-config:
      collector:      "php-config"
      description:    "BadPixxel - PROD - PHP Configuration"
      enabled:        false
      rules:
          # PHP Version
          PHP_VERSION:            { collector: "php-constant", rule: version, gt: { error: "7.2.0" }, lt: { warning: "8.0" } }

          # PHP Core Config
          date.timezone:          { ne: { emergency: true }, eq: { warning: "Europe/Paris" } }
          realpath_cache_size:    { gte: "2048" }
          realpath_cache_ttl:     { gte: { error: "300", notice: "600" } }
          session.auto_start:     { eq: false }

          # APCU Cache Configuration
          apc.enabled:            { eq: { warning: true} }
          apc.enable_cli:         { eq: { warning: true} }

          # Op Cache Configuration
          opcache.enable:                 { eq: true }
          opcache.enable_cli:             { eq: { warning: true} }
          opcache.enable_file_override:   { eq: { warning: true} }
          opcache.max_accelerated_files:  { gte: { warning: 10000, info: 35000} }
          opcache.memory_consumption:     { gte: { warning: 256 } }
          opcache.validate_timestamps:    { eq: { warning: true} }

  bp-prod-php-ext:
      collector:      "php-ext"
      description:    "BadPixxel - PROD - PHP Extensions"
      enabled:        false
      rules:
          apcu:         { ne: true }
          soap:         { ne: true }
          curl:         { ne: true }
          date:         { ne: true }
          gd:           { ne: true }
          intl:         { ne: true }
          json:         { ne: true }
          mbstring:     { ne: true }
          mongodb:      { ne: { warning: true}, gt: { warning: "1.6" },  }
          pdo_mysql:    { ne: true }
          posix:        { ne: true }
          tokenizer:    { ne: true }
          xml:          { ne: true }
