################################################################################
#
# Copyright (C) 2020 BadPixxel <www.badpixxel.com>
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
################################################################################

################################################################
# Defined Pipeline Stages
stages:
  - docker
  - tests
  - deploy

################################################################
# Functional Tests
################################################################

.core_tests:    &core_tests
    stage:      tests
    tags:       [ Dedicated ]
    services:
      - mysql:5.7
    ################################################################################
    # Install & Configure Environment
    before_script:
        - cp .env.test .env
        # Run Composer to Build Dependencies
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/composer.sh  | bash
        # Fix Cs for Autogenerated Files
        - php vendor/bin/php-cs-fixer --allow-risky=yes --config=vendor/badpixxel/php-sdk/phpcs/cs.badpixxel.php fix config

    ################################################################################
    # Run Test Script
    script:
        # Execute Grumphp Testsuite
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/grumphp.sh  | sh
        # Execute PhpUnit Tests
        - vendor/bin/phpunit

    ################################################################################
    # Run After Script
    after_script:
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/after.sh | sh

tests:php-7.4:
  image: registry.gitlab.com/badpixxel-projects/php-sdk:php-7.4
  <<: *core_tests

tests:php-7.3:
  image: registry.gitlab.com/badpixxel-projects/php-sdk:php-7.3
  <<: *core_tests

tests:php-7.2:
  image: registry.gitlab.com/badpixxel-projects/php-sdk:php-7.2
  <<: *core_tests


################################################################
# Build Docker Images
################################################################
docker:
  stage:        docker
  image:        docker:stable
  tags:         [ Dedicated-Docker ]
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - echo "[PADDOCK] Build & Upload Docker Image"
    # Connect Docker to GitLab
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    # Build & Upload Docker Image
    - docker build -t registry.gitlab.com/badpixxel-projects/paddock:latest docker/paddock
    - docker push registry.gitlab.com/badpixxel-projects/paddock:latest

#################################################################
## Build Documentation
#################################################################
pages:
    image:      registry.gitlab.com/badpixxel-projects/php-sdk:jekyll
    stage:      deploy
    retry:      2
    tags:       [ Dedicated ]
    ################################################################################
    # Run Test Script
    script:
        - cp .env.test .env
        # Run Composer to Build Dependencies
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/composer.sh  | bash
        # Build Documentation
        - php vendor/bin/grumphp run --tasks=build-docs
        # Export Configurations
        - php bin/console paddock:export public/paddock.yml
    artifacts:
        paths:
            - public
