
################################################################################
#
# Copyright (C) 2021 BadPixxel <www.badpixxel.com>
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
################################################################################

################################################################################
# Docker Compose File
################################################################################

version: "3.5"

services:

    ################################################################################
    # Application Container
    app:
        image: 'registry.gitlab.com/badpixxel-projects/php-sdk:php-8.0'
        container_name: dev.paddock.local
        volumes:
            - symfony-var:/var/www/html/var
            - './:/var/www/html:ro'
            - './tests/Fixtures:/var/www/source'
            - ./docker/ssh-config:/etc/ssh:ro
        hostname:           dev.paddock.local
        networks:
            paddock:        { ipv4_address: 172.202.0.10, aliases: [ dev.paddock.local ] }

    ################################################################################
    # Paddock Deploy Container
    paddock:
        build:
            context: ./docker/paddock
        container_name: deploy.paddock.local
        hostname:           deploy.paddock.local

    ################################################################################
    # MySQL Container
    mysql:
        image: mysql:5.7
        container_name: mysql.paddock.local
        environment:
            - "MYSQL_ROOT_PASSWORD=admin"
            - "MYSQL_DATABASE=paddock"
        logging: { driver: "none" }
        networks:
            paddock:        { ipv4_address: 172.202.0.11, aliases: [ mysql.paddock.local ] }

    ################################################################################
    # MongoDb Container
    mongodb:
        image: mongo:latest
        container_name: mongo.paddock.local
        logging: { driver: "none" }
        networks:
            paddock:        { ipv4_address: 172.202.0.12, aliases: [ mongo.paddock.local ] }

    ################################################################################
    # Configuration Storage Container
    configs:
        image: atmoz/sftp:alpine
        container_name: configs.paddock.local
        volumes:
            - ./src:/home/admin
        ports:
            - "2222:22"
        command: admin:p@ssword
        networks:
            paddock:      { ipv4_address: 172.202.0.20, aliases: [ configs.paddock.local ] }

    ################################################################################
    # Rdiff Backup Location Storage Container
    backup-1:
        image: achaiah/docker-rdiff-backup
        container_name: backup-1.paddock.local
        environment:
          - CNTUSER=admin
          - CNTPASS=p@ssword
          - ROOTPASS=p@ssword
          - PGID=1000
          - PUID=1000
        volumes:
            - ./docker/ssh-config:/etc/ssh:ro
        networks:
            paddock:      { ipv4_address: 172.202.0.31, aliases: [ backup-1.paddock.local ] }

    ################################################################################
    # PhpMyAdmin Container
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5
        container_name: phpmyadmin.paddock.local
        logging: { driver: "none" }
        depends_on:
            - mysql
        environment:
            - PMA_HOST=mysql
            - MYSQL_USER=admin
            - MYSQL_ROOT_PASSWORD=admin
            - MYSQL_PASSWORD=admin
        networks:
            paddock:      { ipv4_address: 172.202.0.200, aliases: [ phpmyadmin.paddock.local ] }

volumes:
    symfony-var:    ~

networks:
    ################################################################################
    # Default Private Network
    paddock:
        driver: bridge
        ipam:
            config:
                - subnet: 172.202.0.0/24
