
########################################################################
#   PADDOCK CORE CACHE POOLS
########################################################################

framework:
    cache:
        pools:
            paddockConfigs:
                adapter:            cache.adapter.filesystem
                default_lifetime:   60
            paddockCollectors:
                adapter:            cache.adapter.filesystem
                default_lifetime:   120
