
services:

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    ########################################################################
    #   PADDOCK CORE SERVICES
    ########################################################################

    BadPixxel\Paddock\Core\Services\LogManager: ~

    BadPixxel\Paddock\Core\Services\ConfigurationManager:
        arguments:
            - "%kernel.project_dir%"

    BadPixxel\Paddock\Core\Services\RulesManager:
        public: true

    BadPixxel\Paddock\Core\Services\CollectorsManager:
        public: true
        arguments:
            - !tagged_iterator { tag: 'paddock.collector', default_index_method: 'getCode' }

    BadPixxel\Paddock\Core\Services\TracksManager:
        public: true
        arguments:
            - "%kernel.project_dir%"

    BadPixxel\Paddock\Core\Services\TracksRunner:
        public: true

    ########################################################################
    #   PADDOCK EVENTS SUBSCRIBER
    ########################################################################

    BadPixxel\Paddock\Core\EventSubscriber\:
        resource: '../../EventSubscriber/'
        tags:    [ kernel.event_subscriber ]

    ########################################################################
    #   PADDOCK CLI COMMANDS
    ########################################################################

    BadPixxel\Paddock\Core\Command\:
        resource: '../../Command/'
        tags:    [ console.command ]